[custom]
enable_rule_generator=true
overwrite_original_rules=true
;设置规则标志位
ruleset=DIRECT,https://zbssa.github.io/rule/clash/my-direct.list
;ruleset=chatgpt,https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Rule/OpenAI.list
ruleset=chatgpt,https://zbssa.github.io/rule/clash/my-chatgpt3.list
ruleset=chatgpt,https://cdn.jsdelivr.net/gh/VPSDance/ai-proxy-rules@main/rules/clash/global.yaml
ruleset=chatgpt,https://raw.githubusercontent.com/VPSDance/ai-proxy-rules/refs/heads/main/rules/clash/openai.yaml
;ruleset=emby,https://zbssa.github.io/rule/clash/my-emby.list
ruleset=海外服务,https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Rule/OpenAI.list
ruleset=海外服务,https://zbssa.github.io/rule/clash/my-chatgpt.list
ruleset=海外服务,https://zbssa.github.io/rule/clash/my-emby.list
ruleset=海外服务,https://zbssa.github.io/rule/clash/my-proxy.list
ruleset=REJECT,https://zbssa.github.io/rule/clash/my-reject.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/LocalAreaNetwork.list
ruleset=微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Microsoft/Microsoft.list
ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanAD.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyList.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyListChina.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyPrivacy.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanProgramAD.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Steam.list
ruleset=学术网站,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Scholar.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/SteamCN.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/GoogleCN.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Apple.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyGFWlist.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyLite.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyMedia.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Telegram.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Porn.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Netflix.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Download.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/CN.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaIp.list
;ruleset=DIRECT,[]GEOIP,CN
ruleset=漏网之鱼,[]MATCH
;设置规则标志位




; [proxy_group]
;设置分组标志位
custom_proxy_group=海外服务`select`[]自动选择`[]DIRECT`.*`http://www.gstatic.com/generate_204`600
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`600
custom_proxy_group=微软服务`select`[]DIRECT`[]海外服务`http://www.gstatic.com/generate_204`600
custom_proxy_group=学术网站`select`[]DIRECT`[]海外服务`http://www.gstatic.com/generate_204`600
;custom_proxy_group=emby`select`(Emby)`[]海外服务
custom_proxy_group=chatgpt`select`(Chat|gpt|GPT|美国)
custom_proxy_group=漏网之鱼`select`[]DIRECT`[]海外服务`http://www.gstatic.com/generate_204`600
;设置分组标志位

; [common]

;# true=开启字母排序，false=保持订阅原始顺序
;#sort_flag=false
;# sort=1 正序 A-Z；sort=-1 逆序 Z-A
;# sort=-1
;# JS排序脚本（整段一行，直接复制）
;#sort_script=function compare(a,b){let getRemark=x=>JSON.parse(x.ProxyInfo).Remark;let na=getRemark(a),nb=getRemark(b);const rank={"香港":1,"新加坡":2,"日本":3,"台湾":4,"韩国":5,"澳门":6,"美国":90,"加拿大":91,"澳洲":92,"其他":999};function getRank(name){for(let key in rank){if(name.includes(key))return rank[key];}return 999;}return getRank(na)-getRank(nb);}

#



;append_proxy_type=false
; proxy_subscription=SYSTEM
; proxy_ruleset=SYSTEM
;proxy_config=SYSTEM
; get out of here (!
;clash_rule_base=https://raw.githubusercontent.com/DoingDog/clashconf/main/base.yaml
; exclude_remarks=(到期|剩余流量|时间|官网|产品|平台|更新|客服)
; do you play games?
; exclude_remarks=(G-|游戏)

; [node_pref]
; love tls1.3
;tls13_flag=true
; no you don't play games
;udp_flag=true
; though useless
;tcp_fast_open_flag=true
;append_sub_userinfo=true
; no
;filter_deprecated_nodes=true
; looks better
;clash_proxies_style=block
;clash_use_new_field_name=true

; [userinfo]
; useless?
; stream_rule=^剩余流量：(.*?)\|总流量：(.*)$|total=$2&left=$1
; time_rule=^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$|$1:$2:$3:$4:$5:$6

; [managed_config]
config_update_interval = 86400



;# 系统代理跳过列表 cfw-bypass
;# System proxy will ignore these domains(or ipnet)
;# 系统代理跳过列表-备份的，不起作用，
;# 使用时可以将cfw-bypass-bak与cfw-bypass内容互换
;#cfw-bypass-bak:
  # 原有字段不用删除

;# 系统代理跳过列表 起作用的
cfw-bypass:
;  # 直连列表
;  # MyList
;  #- qq.com
;  #- 'music.163.com' # 网易云域名1
;  #- '*.music.126.net' # 网易云域名2
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>

