[custom]
enable_rule_generator=true
overwrite_original_rules=true
;设置规则标志位
ruleset=DIRECT,https://zbssa.github.io/rule/clash/my-direct.list
;ruleset=chatgpt,https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Rule/OpenAI.list
ruleset=chatgpt,https://zbssa.github.io/rule/clash/my-chatgpt.list
ruleset=chatgpt,https://raw.githubusercontent.com/VPSDance/ai-proxy-rules/refs/heads/main/rules/clash/openai.yaml
;ruleset=emby,https://zbssa.github.io/rule/clash/my-emby.list
ruleset=海外服务,https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Rule/OpenAI.list
ruleset=海外服务,https://zbssa.github.io/rule/clash/my-chatgpt.list
ruleset=海外服务,https://zbssa.github.io/rule/clash/my-emby.list
ruleset=海外服务,https://zbssa.github.io/rule/clash/my-proxy.list
ruleset=REJECT,https://zbssa.github.io/rule/clash/my-reject.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/LocalAreaNetwork.list
ruleset=微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Microsoft/Microsoft.list
ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanAD.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyList.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyListChina.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyPrivacy.list
;ruleset=REJECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanProgramAD.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Steam.list
ruleset=学术网站,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Scholar.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/SteamCN.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/GoogleCN.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Apple.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyGFWlist.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyLite.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyMedia.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Telegram.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Porn.list
ruleset=海外服务,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Netflix.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Download.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/CN.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaIp.list
;ruleset=DIRECT,[]GEOIP,CN
ruleset=漏网之鱼,[]MATCH
;设置规则标志位




; [proxy_group]
;设置分组标志位
custom_proxy_group=海外服务`select`[]自动选择`[]DIRECT`.*`http://www.gstatic.com/generate_204`600
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`600
custom_proxy_group=微软服务`select`[]DIRECT`[]海外服务`http://www.gstatic.com/generate_204`600
custom_proxy_group=学术网站`select`[]DIRECT`[]海外服务`http://www.gstatic.com/generate_204`600
;custom_proxy_group=emby`select`(Emby)`[]海外服务
custom_proxy_group=chatgpt`select`(Chat|gpt|GPT|美国)
custom_proxy_group=漏网之鱼`select`[]DIRECT`[]海外服务`http://www.gstatic.com/generate_204`600
;设置分组标志位

; [common]

# true=开启字母排序，false=保持订阅原始顺序
#sort_flag=false
# sort=1 正序 A-Z；sort=-1 逆序 Z-A
# sort=-1
# JS排序脚本（整段一行，直接复制）
#sort_script=function compare(a,b){let getRemark=x=>JSON.parse(x.ProxyInfo).Remark;let na=getRemark(a),nb=getRemark(b);const rank={"香港":1,"新加坡":2,"日本":3,"台湾":4,"韩国":5,"澳门":6,"美国":90,"加拿大":91,"澳洲":92,"其他":999};function getRank(name){for(let key in rank){if(name.includes(key))return rank[key];}return 999;}return getRank(na)-getRank(nb);}

#



;append_proxy_type=false
; proxy_subscription=SYSTEM
; proxy_ruleset=SYSTEM
;proxy_config=SYSTEM
; get out of here (!
;clash_rule_base=https://raw.githubusercontent.com/DoingDog/clashconf/main/base.yaml
exclude_remarks=(到期|剩余流量|时间|官网|产品|平台|更新|客服)
; do you play games?
; exclude_remarks=(G-|游戏)

; [node_pref]
; love tls1.3
;tls13_flag=true
; no you don't play games
;udp_flag=true
; though useless
;tcp_fast_open_flag=true
;append_sub_userinfo=true
; no
;filter_deprecated_nodes=true
; looks better
;clash_proxies_style=block
;clash_use_new_field_name=true

; [userinfo]
; useless?
stream_rule=^剩余流量：(.*?)\|总流量：(.*)$|total=$2&left=$1
time_rule=^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$|$1:$2:$3:$4:$5:$6

; [managed_config]
config_update_interval = 86400



# 系统代理跳过列表 cfw-bypass
# System proxy will ignore these domains(or ipnet)
# 系统代理跳过列表-备份的，不起作用，
# 使用时可以将cfw-bypass-bak与cfw-bypass内容互换
#cfw-bypass-bak:
  # 原有字段不用删除

# 系统代理跳过列表 起作用的
cfw-bypass:
  # 直连列表
  # MyList
  #- qq.com
  #- 'music.163.com' # 网易云域名1
  #- '*.music.126.net' # 网易云域名2
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>



;[节点重命名]
;Rename remarks with the following patterns. Supports regular expression.
;Format: Search_Pattern@Replace_Pattern


rename_node=\[[^\]]*?\]@
;rename_node=[Anytls]@
;rename_node=[Vless]@
;rename_node=[HY2]@
;rename_node=[偏远]@
;rename_node=x@
;rename_node=\[([^\[\]]*)\]@
;rename_node=(\([^\)]*\))@
;rename_node=@.*$@
;rename_node=流媒体解锁@
;rename_node=解锁流媒体@
;rename_node=No.@


;特殊符号
;rename_node=移动@移
;rename_node=电信@电
;rename_node=联通@联
;rename_node=IPLC@专线
;rename_node=RELAY@中转
;rename_node=BGP-@
;rename_node=IEPL@
;rename_node=HK-@
;rename_node=JP-@
;rename_node=SG-@
;rename_node=KR-@
;rename_node=TW-@
;rename_node=US-@
;rename_node=TR-@
;rename_node=RU-@
;rename_node=AU-@
;rename_node=CA-@
;rename_node=UK-@
;rename_node=DE-@
;rename_node=TH-@



; short names
;rename_node=中国@中
;rename_node=徐州@徐
;rename_node=深圳@深
;rename_node=上海@沪
;rename_node=广州@穗
;rename_node=宁波@甬
;rename_node=贵阳@筑
;rename_node=武汉@汉
;rename_node=南京@宁
;rename_node=天津@津
;rename_node=北京@京
;rename_node=沈阳@沈
;rename_node=江苏@苏
;rename_node=浙江@浙
;rename_node=安徽@皖
;rename_node=湖北@鄂
;rename_node=福建@闽
;rename_node=湖南@湘
;rename_node=广东@粤
;rename_node=海南@琼
;rename_node=四川@川
;rename_node=贵州@贵
;rename_node=江西@赣
;rename_node=云南@云
;rename_node=青海@青
;rename_node=台湾@台
;rename_node=香港@港
;rename_node=澳门@澳
;rename_node=美国@美
;rename_node=英国@英
;rename_node=加拿大@加
;rename_node=法国@法
;rename_node=德国@德
;rename_node=瑞士@瑞
;rename_node=日本@日
;rename_node=韩国@韩
;rename_node=芬兰@芬
;rename_node=印度@印
;rename_node=泰国@泰
;rename_node=越南@越
;rename_node=新加坡@新
;rename_node=意大利@意
;rename_node=菲律宾@菲
;rename_node=俄罗斯@俄
;rename_node=土耳其@土
;rename_node=墨西哥@墨
;rename_node=澳大利亚@澳
;rename_node=西班牙@西
;rename_node=马来西亚@马
;rename_node=巴西@巴
;rename_node=东京@日
;rename_node=法兰克福@德
;rename_node=西雅图@美

; times RE
;rename_node=\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?@-$1x
;rename_node=\s*\-+\s*@-

;[managed_config]
;Append a '#!MANAGED-CONFIG' info to Surge configurations
;write_managed_config=true

;Address prefix for MANAGED-CONFIG info, without the trailing "/".
;managed_config_prefix=http://127.0.0.1:25500

;[surge_external_proxy]
;surge_ssr_path=/usr/bin/ssr-local

[emojis]
add_emoji=false
remove_old_emoji=true

;Rule to add emojis. Supports regular expression.
;Format: Remark_Search_Pattern,emoji
;rule=(流量|时间|应急|过期|Bandwidth|expire),🏳️‍🌈
;rule=AC,🇦🇨
;rule=(AR|阿根廷),🇦🇷
;rule=(奥地利|维也纳),🇦🇹
;rule=(AU|Australia|Sydney|澳大利亚|悉尼),🇦🇺
;rule=BE,🇧🇪
;rule=(BR|Brazil|巴西|圣保罗),🇧🇷
;rule=(Canada|加拿大|蒙特利尔|温哥华|楓葉|枫叶),🇨🇦
;rule=(瑞士|苏黎世),🇨🇭
;rule=(DE|Germany|德国|法兰克福|德),🇩🇪
;rule=丹麦,🇩🇰
;rule=ES,🇪🇸
;rule=EU,🇪🇺
;rule=(Finland|芬兰|赫尔辛基),🇫🇮
;rule=(FR|France|法国|巴黎),🇫🇷
;rule=(UK|England|UnitedKingdom|英国|英|伦敦),🇬🇧
;rule=(HK|HongKong|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港|港),🇭🇰
;rule=(Indonesia|印尼|印度尼西亚|雅加达),🇮🇩
;rule=(Ireland|爱尔兰|都柏林),🇮🇪
;rule=(India|印度|孟买),🇮🇳
;rule=(Italy|意大利|米兰),🇮🇹
;rule=(JP|Japan|日本|东京|大阪|埼玉|沪日|穗日|川日|中日|泉日|杭日),🇯🇵
;rule=(KP|朝鲜),🇰🇵
;rule=(KR|Korea|KOR|韩国|首尔|韩|韓),🇰🇷
;rule=(MO|Macao|澳门|CTM),🇲🇴
;rule=(MY|Malaysia|马来西亚),🇲🇾
;rule=(NL|Netherlands|荷兰|阿姆斯特丹),🇳🇱
;rule=(PH|Philippines|菲律宾),🇵🇭
;rule=(RO|罗马尼亚),🇷🇴
;rule=(RU|Russia|俄罗斯|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|京俄|杭俄),🇷🇺
;rule=(沙特|迪拜),🇸🇦
;rule=(SE|Sweden),🇸🇪
;rule=(SG|Singapore|新加坡|狮城|沪新|京新|泉新|穗新|深新|杭新),🇸🇬
;rule=(TH|Thailand|泰国|曼谷),🇹🇭
;rule=(TR|Turkey|土耳其|伊斯坦布尔),🇹🇷
;rule=(US|America|UnitedStates|美国|美|京美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美),🇺🇲
;rule=(VN|越南),🇻🇳
;rule=(ZA|南非),🇿🇦
;rule=(CN|China|回国|中国|江苏|北京|上海|广州|深圳|杭州|常州|徐州|青岛|宁波|镇江|back|TW|Taiwan|台湾|台北|台中|新北|彰化|CHT|新北|台|HINET),🇨🇳

